import { Test, TestingModule } from '@nestjs/testing';
import { FileService } from './file.service';
import { Team } from "../objects/Team";
import { unlinkSync } from "fs";

fdescribe('FileService', () => {
  let service: FileService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [FileService],
    }).compile();

    service = module.get<FileService>(FileService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });


  fit('should save Team[] to file', () => {
    const dir = 'output/';
    const file = 'deleteme.json';
    const teams = generateTeamsObject();
    service.saveTeamsToFile(dir, file, teams);
    const returnTeams = service.readTeamsFileToTeams(dir, file);
    expect(teams).toEqual(returnTeams);
  
    try {
      unlinkSync(`${dir}${file}`);
      // console.log('successfully deleted /tmp/hello');
    } catch (err) {
      // handle the error
      fail();
    }
  })

});

function generateTeamsObject(): Team[] {
  return JSON.parse(`[
  {
    "teamNumber": 662,
    "nameFull": "Academy School District 20 / Verizon / National Defense Education Program / United States Air Force Academy STEM Outreach Program / The Niedringhaus Family / Northrup Grumman / Marco's Pizza / Alvin Fishman, CPA / Fastenal / Red Rock Technologies / Broadcom Limited & Air Academy High School & Discovery Canyon Campus HS & Pine Creek High School & Rampart High School & Tca College Pathways",
    "nameShort": "Rocky Mountain Robotics",
    "city": "USAF Academy",
    "stateProv": "Colorado",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Air Academy High School & Discovery Canyon Campus HS & Pine Creek High School & Rampart High School & Tca College Pathways",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 663,
    "nameFull": "WRT Management Corp./Bach Knives/Waters Corp. & Whitinsville Christian School",
    "nameShort": "Robonauts",
    "city": "Whitinsville",
    "stateProv": "Massachusetts",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": "NE",
    "schoolName": "Whitinsville Christian School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 668,
    "nameFull": "Gilbert-Greenstein Family/KLA- Foundation/BAE/Qualcomm/Intuitive & Family/Community & Pioneer High School",
    "nameShort": "The Apes of Wrath",
    "city": "San Jose",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Family/Community & Pioneer High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 670,
    "nameFull": "FUHSD Foundation/Ronald Crane Trust/KLA Foundation/Ford/Anonymous/Corning Foundation/Applied Materials/Evil Mad Scientist&Homestead High School",
    "nameShort": "Homestead Robotics",
    "city": "Cupertino",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Homestead High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 677,
    "nameFull": "Ohio State University/American Electric Power/Northrop Grumman & Columbus School for Girls",
    "nameShort": "Murphy's Outlaws",
    "city": "Columbus",
    "stateProv": "Ohio",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Columbus School for Girls",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 686,
    "nameFull": "Maryland State Department of Education/Bechtel/Leidos/Leonardo DRS/BAE Systems/Sheetz&Catoctin High School&Linganore High School&Walkersville High School",
    "nameShort": "Bovine Intervention",
    "city": "Thurmont",
    "stateProv": "Maryland",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": "CHS",
    "schoolName": "Catoctin High School & Linganore High School & Walkersville High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 687,
    "nameFull": "Gene Haas Foundation/Boeing/Raytheon/Parker/CAMS PTSO&California Academy Math & Sci",
    "nameShort": "The Nerd Herd",
    "city": "Carson",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "California Academy Math & Sci",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 691,
    "nameFull": "Northrop Grumman/Walt Disney Imagineering/DoD/Boston Scientific/Raytheon Technologies /Boeing&Valencia High School&Hart High School&Saugus High School&Academy of the Canyons&West Ranch High School",
    "nameShort": "Project 691 Robotics",
    "city": "Stevenson Ranch",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Academy of the Canyons & Saugus High School & Hart High School & Valencia High School & West Ranch High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 694,
    "nameFull": "Stuyvesant High School Parents' Association/Belliveau Family/ConEdison/Bloomberg/ABB Inc./L3Harris Technologies/Google/Amazon/Dr. Joe Ricci/Wong Family&Stuyvesant High School",
    "nameShort": "StuyPulse",
    "city": "New York",
    "stateProv": "New York",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Stuyvesant High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 695,
    "nameFull": "Board of Education & Beachwood High School",
    "nameShort": "Bison Robotics",
    "city": "Cleveland",
    "stateProv": "Ohio",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Beachwood High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 696,
    "nameFull": "JPL/Glendale Unified School District/Gene Haas Foundation/Arconic Foundation/Walt Disney Imagineering/Boeing/Honda R&D Americas/MathWorks/Jim & Donna Stone/Widholm Family & Clark Magnet High School",
    "nameShort": "Circuit Breakers",
    "city": "Glendale",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Clark Magnet High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 698,
    "nameFull": "Microchip Technology Inc. / Industrial Metal Supply / M+W Group / Sturm, Ruger and Co. / UnWired Engineering / Heatsync Labs / Tan Pants Media / Wells Fargo  Inc. / Intel & Hamilton High School",
    "nameShort": "Hamilton Microbots",
    "city": "Chandler",
    "stateProv": "Arizona",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Hamilton High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 701,
    "nameFull": "Travis USD/Genentech/Collins Aerospace/Syar Foundation/Solano County Office of Education/Salik Syed/Intuitive Surgical/Vaca Valley Bingo Hall/Pirondini Family/Michael and Margaret Salvador/Meta Design Manufacturing/Dale Salvador and United Way/Paula Green/Travis AFB Spouses Club/Vanden Robotics Foundation&Vanden High School",
    "nameShort": "RoboVikes",
    "city": "Fairfield",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Vanden High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 702,
    "nameFull": "Raytheon/JPL/NASA/Culver City Educational Foundation/Culver City Rotary Club/Pinnacle Industrial Supply & Culver City High School",
    "nameShort": "Bagel Bytes",
    "city": "Culver City",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Culver City High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 703,
    "nameFull": "Dow/FIRST in Michigan/FIRST of the Great Lakes Bay Region /FIRST Robotics/Fullerton Tool Company/Glastender Inc./Michigan Department of Education/Mid-State Bolt & Screw/Netsource One, Inc./Nexteer/Remer Plumbing, Heating, & Air Conditioning, Inc./Saginaw Industries, LLC/Saginaw Career Complex/Serra/Toyota/U.S. Sheet Metal&Saginaw Career Complex",
    "nameShort": "Team Phoenix",
    "city": "Saginaw",
    "stateProv": "Michigan",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": "FIM",
    "schoolName": "Saginaw Career Complex",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 706,
    "nameFull": "Rockwell Automation/Axis Automation/GE&Arrowhead Union High School",
    "nameShort": "Cyberhawks",
    "city": "Hartland",
    "stateProv": "Wisconsin",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Arrowhead Union High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 708,
    "nameFull": "Lockheed Martin/Hatboro-Horsham Education Foundation/The Landreth Family/Mr. Johnson&Hatboro-Horsham Sr High School",
    "nameShort": "Hatters Robotics",
    "city": "Horsham",
    "stateProv": "Pennsylvania",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": "FMA",
    "schoolName": "Hatboro-Horsham Sr High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 709,
    "nameFull": "The Boeing Company / Glaxo-Smith-Kline & Agnes Irwin School",
    "nameShort": "Femme Tech Fatale",
    "city": "Bryn Mawr",
    "stateProv": "Pennsylvania",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": "FMA",
    "schoolName": "Agnes Irwin School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 714,
    "nameFull": "Newark Public Schools District/Titan Engineers PC /CAROL FORD RACING/ARCO STEEL/THE KNOTTS COMPANY/COUSE & BOLTEN CO./SHOP RITE KEARNY/THE INVENTION DESIGN&Technology High School",
    "nameShort": "Panthera",
    "city": "Newark",
    "stateProv": "New Jersey",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": "FMA",
    "schoolName": "Technology High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 716,
    "nameFull": "21st Century Fund/C. A. Lindell  & Son Inc./Freund's Farm Market and Bakery/Jon Higgins&Housatonic Valley Reg High Sch",
    "nameShort": "Who'sCTEKS",
    "city": "Falls Village",
    "stateProv": "Connecticut",
    "country": "USA",
    "rookieYear": 2001,
    "robotName": "",
    "districtCode": "NE",
    "schoolName": "Housatonic Valley Reg High Sch",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 743,
    "nameFull": "Sony/Bloomberg/Con Edison & HS of Computers & Technology",
    "nameShort": "Technobots",
    "city": "Bronx",
    "stateProv": "New York",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "HS of Computers & Technology",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 744,
    "nameFull": "apex machine company/Motorola Solutions Foundation/United Technologies Corporation - Otis Elevator/Loucks Engineering/Hill York Air Conditioning Services & Energy Solutions/The State of Florida&Westminster Academy",
    "nameShort": "Shark Attack",
    "city": "Fort Lauderdale",
    "stateProv": "Florida",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Westminster Academy",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 746,
    "nameFull": "Toronto District School Board/Westview Centennial Secondary School/Microsoft Canada/Thorne Innovations/RBC Wealth Management-PH&N Investment Counsel & Westview Centennial Secondary School",
    "nameShort": "Gearheads 746",
    "city": "North York",
    "stateProv": "Ontario",
    "country": "Canada",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "ONT",
    "schoolName": "Westview Centennial Secondary School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 747,
    "nameFull": "ANSUN Protective Metals/Picatinny Arsenal/Veolia Environmental Services/Nokia Bell Labs/Quality Sheet Metal & Welding/Central Jersey Powder Coat&Family/Community",
    "nameShort": "Flight Crew",
    "city": "Middlesex",
    "stateProv": "New Jersey",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FMA",
    "schoolName": "Family/Community",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 751,
    "nameFull": "RHM Realty/PDF Solutions&Woodside Priory School",
    "nameShort": "barn2robotics",
    "city": "Portola Valley",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Woodside Priory School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 752,
    "nameFull": "Newark Board of Education/Comcast&Science Park High School",
    "nameShort": "The Chargers",
    "city": "Newark",
    "stateProv": "New Jersey",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FMA",
    "schoolName": "Science Park High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 753,
    "nameFull": "iFixit/Thermo Fisher Scientific&Mountain View Sr High School",
    "nameShort": "High Desert Droids",
    "city": "Bend",
    "stateProv": "Oregon",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "PNW",
    "schoolName": "Mountain View Sr High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 766,
    "nameFull": "Lockheed Martin/American Prototype & Production, Inc./Round Table Pizza/Blue River Technology/Google Inc./FIRST NorCal&Menlo-Atherton High School",
    "nameShort": "M-A Bears",
    "city": "Atherton",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Menlo-Atherton High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 771,
    "nameFull": "Collins Aerospace Systems/Hatch/Shaw Almex&St. Mildred's Lightbourn School",
    "nameShort": "SWAT",
    "city": "Oakville",
    "stateProv": "Ontario",
    "country": "Canada",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "ONT",
    "schoolName": "St. Mildred's Lightbourn School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 772,
    "nameFull": "General Motors of Canada/Centerline Windsor Ltd./Brave Control Solutions/SWT Group/St Clair College/University of Windsor/Linamar/KMJ Industrial Contractors /Kuka&Sandwich Secondary School",
    "nameShort": "Sabre Bytes Robotics ",
    "city": "LaSalle",
    "stateProv": "Ontario",
    "country": "Canada",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "ONT",
    "schoolName": "Sandwich Secondary School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 781,
    "nameFull": "Bruce Power/Kinetic Knights Youth Robotics&Family/Community",
    "nameShort": "Kinetic Knights",
    "city": "Kincardine",
    "stateProv": "Ontario",
    "country": "Canada",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "ONT",
    "schoolName": "Family/Community",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 801,
    "nameFull": "Jacobs Technology/Lockheed Martin/Brevard Public Schools/Brevard County Fire Rescue Station 43/Exploration Ground Systems/Excell Coatings Inc./Alro Steel/Intergrated Launch Solutions/PIRTEK/Crest Cleaners/W+J Construction/Precision, Fabrication, and Cleaning/Space Shirts&Merritt Island High School&Edgewood Jr Sr High School&Cocoa Beach Jr Sr High School",
    "nameShort": "Horsepower",
    "city": "Merritt Island",
    "stateProv": "Florida",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Cocoa Beach Jr Sr High School & Merritt Island High School & Edgewood Jr Sr High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 806,
    "nameFull": "D'Onofrio General Contractors Corp./Riva Precision Manufacturing/Ensign-Bickford Industries, Inc.&Xaverian High School",
    "nameShort": "The Brooklyn Blacksmiths",
    "city": "Brooklyn",
    "stateProv": "New York",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Xaverian High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 810,
    "nameFull": "Smithtown Central School District & Smithtown High School-East & Smithtown High School-West",
    "nameShort": "The Mechanical Bulls",
    "city": "Smithtown",
    "stateProv": "New York",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Smithtown High School-East & Smithtown High School-West",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 811,
    "nameFull": "NE FIRST/BAE Systems/Darren & Tuyet Martin&Bishop Guertin High School",
    "nameShort": "Wild Cards",
    "city": "Nashua",
    "stateProv": "New Hampshire",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "NE",
    "schoolName": "Bishop Guertin High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 812,
    "nameFull": "General Motors Foundation / Qualcomm / Solar Turbines / LEIDOS / Nordson ASYMTEK / Abbott / The Preuss School UCSD / University of California at San Diego / Irwin and Joan Jacobs & Preuss School",
    "nameShort": "The Midnight Mechanics",
    "city": "La Jolla",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Preuss School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 815,
    "nameFull": "Ford Motor Company/NASA/DTE Energy/Michigan Department of Education&Allen Park High School&Inter City Baptist School",
    "nameShort": "Advanced Power",
    "city": "Allen Park",
    "stateProv": "Michigan",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIM",
    "schoolName": "Inter City Baptist School & Allen Park High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 816,
    "nameFull": "Lockheed Martin/Comcast NBCUniversal/Burlington County Institute of Technology Foundation/Melton Industries/Biraluci Italian Restaurant and Pizzeria/Blacey's U-Pick Auto Parts/Custom Wood LLC/Townsend Machinery/CSD Design & Fabrication/Summit Racing Equipment&Burlington Co Tech-Westampton",
    "nameShort": "Anomaly",
    "city": "Mount Holly",
    "stateProv": "New Jersey",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FMA",
    "schoolName": "Burlington Co Tech-Westampton",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 818,
    "nameFull": "General Motors/McNaughton-McKay/Rockwell Automation/Envy Engineering/FCA Foundation/Warren Consolidated Schools/Magna/Michigan Department of Education/U.S. Department of Defense&Warren Mott High School&Cousino High School&Sterling Heights High School",
    "nameShort": "The Steel Armadillos 818",
    "city": "Warren",
    "stateProv": "Michigan",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIM",
    "schoolName": "Sterling Heights High School & Warren Mott High School & Cousino High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 829,
    "nameFull": "DoD Stem/Motorola Solutions/the Gene Haas Foundation/Bayer Fund/Waterjet Cutting of Indiana/Colors Inc&Walker Career Center",
    "nameShort": "The Digital Goats",
    "city": "Indianapolis",
    "stateProv": "Indiana",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIN",
    "schoolName": "Walker Career Center",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 830,
    "nameFull": "Ford Motor Company/Bosch/Michigan Department of Education/Toyota Technical Center/Maker Works/Harbor Freight/Ann Arbor Public Schools&Huron High School",
    "nameShort": "The RatPack",
    "city": "Ann Arbor",
    "stateProv": "Michigan",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIM",
    "schoolName": "Huron High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 832,
    "nameFull": "Kennesaw State University/Novelis/Fulton County Schools/92 Threads/Roswell Firelabs/Raypaul Coating/Graphic Packaging International/Dealer Ops/Rockwell International/Wilhoit Gas Company/Roswell High School Robotics Booster Club, Inc/DOW/NASA&Roswell High School",
    "nameShort": "Oscar 832",
    "city": "Roswell",
    "stateProv": "Georgia",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "PCH",
    "schoolName": "Roswell High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 834,
    "nameFull": "The SparTechs Foundation/Lutron/Bosch/Reliable Equipment/Texas Instruments/Knoll/Demco Automation/Bergey's/Sumitomo/Langan/CHL Systems/MSA&Southern Lehigh High School",
    "nameShort": "SparTechs",
    "city": "Easton",
    "stateProv": "Pennsylvania",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FMA",
    "schoolName": "Southern Lehigh High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 835,
    "nameFull": "DENSO & Detroit Country Day High Sch",
    "nameShort": "The Sting",
    "city": "Beverly Hills",
    "stateProv": "Michigan",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIM",
    "schoolName": "Detroit Country Day High Sch",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 836,
    "nameFull": "Stachelczyk-Shemeta Team - Century 21 New Millennium /The Patuxent Partnership/BAE Systems/Northrop Gruman/DOD STEM/Naval Air Warfare Center Aircraft Division (NAWCAD)/growingSTEMS&Family/Community",
    "nameShort": "The RoboBees",
    "city": "Hollywood",
    "stateProv": "Maryland",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "CHS",
    "schoolName": "Family/Community",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 839,
    "nameFull": "NASA/Collins Aerospace/Agawam Robotics Education Association Inc./TW Metals/Agawam Lions Club&Agawam Senior High School",
    "nameShort": "Rosie Robotics",
    "city": "Feeding Hills",
    "stateProv": "Massachusetts",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "NE",
    "schoolName": "Agawam Senior High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 840,
    "nameFull": "Apple/Abbott Laboratories /San Mateo Union High School District/Qualcomm/SolidWorks/NASA/Intuitive Surgical/Google/Lockheed Martin&Aragon High School",
    "nameShort": "Aragon Robotics Team",
    "city": "San Mateo",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Aragon High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 841,
    "nameFull": "Chevron/SunPower/Atlassian/BAE Systems/Intuitive Surgical/Applied Materials/Engineering Partnership Academy & College and Career Center/Applied Lasers LLC/M. Welding Creations and Industrial Finishing&Richmond High School",
    "nameShort": "The BioMechs",
    "city": "Richmond",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Richmond High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 842,
    "nameFull": "Arizona Charitable Tax Credit Donors/Simrex Corporation/Shebbie Jacques/Southwest Fasteners/SOLIDWORKS/SolidCAM&Carl Hayden Cmty High School",
    "nameShort": "Falcon Robotics",
    "city": "Phoenix",
    "stateProv": "Arizona",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Carl Hayden Cmty High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 846,
    "nameFull": "FUHS Foundation/Apple/KLA/ARM/Western Digital Foundation/Intuitive Surgical Inc/Boeing/Corning Foundation/BAE P&S/FIRST NorCal/Gene Haas Foundation/Boston Scientific/Qualcomm/Autodesk&Lynbrook High School",
    "nameShort": "The Funky Monkeys",
    "city": "San Jose",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Lynbrook High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 847,
    "nameFull": "Oregon Department of Education/Autodesk/IBEW Local 280/First Tech Credit Union/Microchip/Maxfield Family/Richard L Siener/Alyrica Internet/Jordan Manufacturing&Philomath High School",
    "nameShort": "PHRED",
    "city": "Philomath",
    "stateProv": "Oregon",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "PNW",
    "schoolName": "Philomath High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 848,
    "nameFull": "NASA & Rolling Hills Preparatory Sch",
    "nameShort": "HuskyBots",
    "city": "San Pedro",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Rolling Hills Preparatory Sch",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 849,
    "nameFull": "PowerStream & Unionville High School",
    "nameShort": "Wolfpack",
    "city": "Unionville",
    "stateProv": "Ontario",
    "country": "Canada",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "ONT",
    "schoolName": "Unionville High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 852,
    "nameFull": "Apple/Abbott Laboratories/Google&Athenian School",
    "nameShort": "Athenian Robotics Collective",
    "city": "Danville",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Athenian School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 854,
    "nameFull": "TDSB/Hatch Ltd/Google&Martingrove Collegiate Institute",
    "nameShort": "Iron Bears",
    "city": "Etobicoke",
    "stateProv": "Ontario",
    "country": "Canada",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "ONT",
    "schoolName": "Martingrove Collegiate Institute",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 857,
    "nameFull": "General Motors/State of Michigan/Solidworks/Great Lakes Sound and Vibration/ThermoAnalytics, Inc./Superior Graphics/GS Engineering/Copper Country Robotics&Houghton High School",
    "nameShort": "Superior Roboworks",
    "city": "Houghton",
    "stateProv": "Michigan",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIM",
    "schoolName": "Houghton High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 858,
    "nameFull": "Pridgeon & Clay/GE Aviation/General Motors/Witvoet and Sons/Wyoming Public Schools&Wyoming High School",
    "nameShort": "Demons Robotics 858",
    "city": "Wyoming",
    "stateProv": "Michigan",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIM",
    "schoolName": "Wyoming High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 862,
    "nameFull": "BOSCH/Jabil/Nissan/Yazaki/Ford&Plymouth High School&Salem High School&Canton High School",
    "nameShort": "Lightning Robotics",
    "city": "Canton",
    "stateProv": "Michigan",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIM",
    "schoolName": "Canton High School & Salem High School & Plymouth High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 865,
    "nameFull": "Toronto District School Board/Motorola Solutions Foundation/Wealthsimple Foundation/BWXT/Google/The Optimist Club of Etobicoke/DBG Canada/AFA Systems Ltd./WARP7 Parents & Supporters & Western Technical-Commercial School",
    "nameShort": "WARP7",
    "city": "Toronto",
    "stateProv": "Ontario",
    "country": "Canada",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "ONT",
    "schoolName": "Western Technical-Commercial School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 867,
    "nameFull": "NASA JPL/Arcadia Unified School District&Arcadia Senior High School",
    "nameShort": "Absolute Value",
    "city": "Arcadia",
    "stateProv": "California",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Arcadia Senior High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 868,
    "nameFull": "Apyx Medical&Carmel Senior High School",
    "nameShort": "TechHOUNDS",
    "city": "Carmel",
    "stateProv": "Indiana",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": "FIN",
    "schoolName": "Carmel Senior High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 870,
    "nameFull": "Charles & Helen Reichert Family Foundation, Inc./Crowley Marine Contracting/STIDD Systems Inc./WM. J. Mills & Co./Ultra Motion LLC/Costello Marine Contracting/The Suffolk Times/Woodside Orchards/The Crean Family/North Fork Welding & Steel/Beachwood Sand & Gravel/Condon Engineering/Lakeside Landscaping/North Fork Sanitation/Port Of Egypt Marine/Southold Hardware/Southold PBA/Suffolk County Police Conference/Albertson Marine/Brian Arm, PT/DJK Heating & Cooling/Eastern Rentals/Hetro LLC/Hustler Powerboats/Island Fiberglass/Jernick Moving & Storage/LI Cauliflower Assoc./Roy H. Reeve Insurance/Southold Fish Market&Southold Jr Sr High School",
    "nameShort": "TEAM  R. I. C. E.  ",
    "city": "Southold",
    "stateProv": "New York",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Southold Jr Sr High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 871,
    "nameFull": "West Islp School District/Zebra Technologies/West Islip Robotics Booster Club, Inc./The DiStefano Family/West Islip Country Fair/Ondrives US/Microchip/Gran Prints/EnerSys/Premier Payroll Solutions/C&D Marine Service Inc. & West Islip Senior High School",
    "nameShort": "Robotechs",
    "city": "West Islip",
    "stateProv": "New York",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "West Islip Senior High School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 876,
    "nameFull": "ND Space Grant/John Deere/Brent Pederson/Dr. Mary Aaland/Northwood Mens Club/Sue Lloyd/Hatton Mens Club/ND CTEd/Kathy LaFleur/Phil and Trish Gisi/Derek/Robin Lloyd&Hatton Eileson School&Northwood School",
    "nameShort": "Thunder Robotics",
    "city": "Hatton-Northwood",
    "stateProv": "North Dakota",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "Hatton Eileson School & Northwood School",
    "website": "",
    "homeCMP": "CMPTX"
  },
  {
    "teamNumber": 877,
    "nameFull": "UND Space Grant Consortium/North Dakota Career and Technical Education&North Star Public School",
    "nameShort": "Pi Rho 'botics @ North Star",
    "city": "Cando",
    "stateProv": "North Dakota",
    "country": "USA",
    "rookieYear": 2002,
    "robotName": "",
    "districtCode": null,
    "schoolName": "North Star Public School",
    "website": "",
    "homeCMP": "CMPTX"
  }
]`)
}
